# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 03:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaddocount', models.IntegerField(default=0, verbose_name='访问次数')),
                ('code', models.CharField(max_length=8, verbose_name='code')),
                ('datatime', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
                ('path', models.CharField(max_length=32, verbose_name='下载路径')),
                ('name', models.CharField(default='', max_length=32, verbose_name='文件名')),
                ('filesize', models.CharField(max_length=10, verbose_name='文件大小')),
                ('pcip', models.CharField(default='', max_length=32, verbose_name='IP地址')),
            ],
            options={
                'db_table': 'download',
                'verbose_name': 'download',
            },
        ),
    ]
